name: Run when Build In scrape or its testing gets changed

on:
  push:
    paths:
      - src/scraping/builtInScrape.py
      - unit_tests/test_builtInScrape.py

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test
        run: |
          make test